import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/permissions";
import { toggleUser } from "./actions";
import { UserForm } from "./user-form";

export default async function UsersPage() {
  const admin = await requireAdmin(); const users = await prisma.user.findMany({ orderBy: [{ isActive: "desc" }, { name: "asc" }] });
  return <div className="space-y-7"><header><p className="text-sm font-bold text-[var(--brand)]">Administration</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight sm:text-3xl">Utilisateurs</h1><p className="mt-2 text-sm text-[var(--ink-soft)]">Créez les accès et désactivez les comptes qui ne doivent plus se connecter.</p></header><div className="grid gap-5 xl:grid-cols-[1fr_22rem]"><section className="overflow-hidden rounded-2xl border border-[var(--line)] bg-white"><div className="divide-y divide-[var(--line)]">{users.map(user => <article key={user.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><div className="flex items-center gap-2"><strong>{user.name}</strong><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${user.role === "ADMIN" ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-700"}`}>{user.role === "ADMIN" ? "Administrateur" : "Employé"}</span></div><p className="mt-1 text-xs text-[var(--ink-soft)]">@{user.username} · {user.isActive ? "Compte actif" : "Compte désactivé"}</p></div><form action={toggleUser}><input type="hidden" name="userId" value={user.id} /><button disabled={user.id === admin.id} className={`min-h-10 rounded-xl px-4 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-40 ${user.isActive ? "border border-red-200 text-red-700" : "bg-[var(--brand)] text-white"}`}>{user.isActive ? "Désactiver" : "Réactiver"}</button></form></article>)}</div></section><aside className="h-fit rounded-2xl border border-[var(--line)] bg-white p-5"><h2 className="font-extrabold">Nouveau compte</h2><p className="mb-5 mt-1 text-sm text-[var(--ink-soft)]">Aucune inscription publique n’est autorisée.</p><UserForm /></aside></div></div>;
}
